description = "fizz buzz buildpack detection at its best"

[lifecycle]
  version = "0.4.0"

[[buildpacks]]
  id = "com.starkandwayne.buildpacks.playtime.fizz"
  uri = "buildpacks/fizz"
  version = "1.0.0"

[[buildpacks]]
  id = "com.starkandwayne.buildpacks.playtime.buzz"
  uri = "buildpacks/buzz"
  version = "1.0.0"

[[order]]

  [[order.group]]
    id = "com.starkandwayne.buildpacks.playtime.fizz"
    version = "1.0.0"

  [[order.group]]
    id = "com.starkandwayne.buildpacks.playtime.buzz"
    version = "1.0.0"

[stack]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
  build-image = "cloudfoundry/cnb-build:cflinuxfs3"
  run-image = "cloudfoundry/cnb-run:cflinuxfs3"
