description = "fizz buzz buildpack detection at its best"

[lifecycle]
  version = "0.4.0"

[[buildpacks]]
  id = "com.starkandwayne.buildpacks.playtime.display-count"
  uri = "buildpacks/display-count"

[[buildpacks]]
  id = "com.starkandwayne.buildpacks.playtime.fizz"
  uri = "buildpacks/fizz"

[[buildpacks]]
  id = "com.starkandwayne.buildpacks.playtime.buzz"
  uri = "buildpacks/buzz"

[[order]]

  [[order.group]]
    id = "com.starkandwayne.buildpacks.playtime.display-count"
    optional = false

  [[order.group]]
    id = "com.starkandwayne.buildpacks.playtime.fizz"
    optional = true

  [[order.group]]
    id = "com.starkandwayne.buildpacks.playtime.buzz"
    optional = true

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "cloudfoundry/build:base-cnb"
  run-image = "cloudfoundry/run:base-cnb"
