description = "fizz buzz buildpack detection at its best"

[lifecycle]
  version = "0.4.0"

[[buildpacks]]
  id = "com.starkandwayne.buildpacks.playtime.fizz"
  uri = "buildpacks/fizz"

[[buildpacks]]
  id = "com.starkandwayne.buildpacks.playtime.buzz"
  uri = "buildpacks/buzz"

[[order]]

  [[order.group]]
    id = "com.starkandwayne.buildpacks.playtime.fizz"
    optional = true

  [[order.group]]
    id = "com.starkandwayne.buildpacks.playtime.buzz"
    optional = true

[stack]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
  build-image = "cloudfoundry/cnb-build:cflinuxfs3"
  run-image = "cloudfoundry/cnb-run:cflinuxfs3"
