# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "com.starkandwayne.buildpacks.playtime.buzz"
version = "1.0.0"
name = "Buzz Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"